# -*- coding: utf-8 -*-
"""ion_knn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Mh-2y1-exti5PxjjKKM_4eeskrpR2PH
"""

pip install ucimlrepo

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from ucimlrepo import fetch_ucirepo
import time

# fetch dataset
ionosphere = fetch_ucirepo(id=52)

# data (as pandas dataframes)
X = ionosphere.data.features
y = ionosphere.data.targets

X = X.values
label = y.values.ravel()

# Define the range of k values
k_values = list(range(2, 34))

avg_accuracy_pca = []
avg_accuracy_ddrp = []

for k in k_values:
    accuracy_pca = []
    accuracy_ddrp = []
    accaracy_rp = []
    for _ in range(20):
      pca = PCA(n_components=k)
      X_train, X_test, X_train_label, X_test_label = train_test_split(X, label, test_size=0.2, random_state=None)
      scaler = StandardScaler()
      scaler.fit(X_train)
      X_train = scaler.transform(X_train)
      X_test = scaler.transform(X_test)
      X_train_pca = pca.fit_transform(X_train)
      X_test_pca = pca.transform(X_test)
      knn = KNeighborsClassifier(n_neighbors=8)
      knn.fit(X_train_pca, X_train_label)
      accuracy_pca.append(knn.score(X_test_pca, X_test_label))

      n, p = X_train.shape
      R = np.zeros((p, k))
      for i in range(k):
        beta = np.random.randn(n)
        R[:, i] = X_train.T @ beta
      T1 = np.matmul(R.T,R)
      T1 = np.linalg.inv(T1)
      T2 = np.matmul(R.T,X_train.T)
      T2 = np.matmul(T1,T2)

      X_train_tilde = np.dot(R, T2)
      X_train_tilde = X_train_tilde.T

      X_train_projected_ddrp = X_train_tilde

      n, p = X_test.shape
      R = np.zeros((p, k))
      for i in range(k):
        beta = np.random.randn(n)
        R[:, i] = X_test.T @ beta
      T1 = np.matmul(R.T,R)
      T1 = np.linalg.inv(T1)
      T2 = np.matmul(R.T,X_test.T)
      T2 = np.matmul(T1,T2)

      X_test_tilde = np.dot(R, T2)
      X_test_tilde = X_test_tilde.T

      X_test_projected_ddrp = X_test_tilde

      knn.fit(X_train_projected_ddrp, X_train_label)
      accuracy_ddrp.append(knn.score(X_test_projected_ddrp, X_test_label))

    avg_accuracy_pca.append(np.mean(accuracy_pca))
    avg_accuracy_ddrp.append(np.mean(accuracy_ddrp))



plt.figure(figsize=(12, 8))
plt.plot(k_values, avg_accuracy_pca, marker='o', linestyle='-', label="PCA")
plt.plot(k_values, avg_accuracy_ddrp,marker='x',linestyle='-',label="Original Data dependent random projection")
plt.title('k vs. Accuracy for Different Projection Methods using KNN')
plt.xlabel('k (Number of Projected Dimensions)')
plt.ylabel('accuracy')
plt.legend()
plt.grid(True)
plt.savefig("extended_v2_rmse_vs_k_comparison.png")
plt.show()